sudo: required

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode7

services:
  - docker

install:
  - ./test/travis-ci/install.sh

script:
  - source setup-env.sh
  - python test/runtest.py
